[tool.poetry]
name = "netsim"
version = "0.1.0"
description = "Network Topology Simulator for eBPF XDP Development"
authors = ["Peter <peter@gmail.com>"]
readme = "README.md"
packages = [{include = "netsim"}]

[tool.poetry.dependencies]
python = ">=3.9,<4.0"
PyYAML = "*"
ruff = "^0.14.14"
mypy = "^1.19.1"
types-pyyaml = "^6.0.12.20250915"

[tool.poetry.scripts]
netsim = "netsim.cli:main"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
